include: custom_analyze_options.yaml
analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/generated/**
    - lib/**.freezed.dart
    - lib/**.g.dart
    - build/**
    - .dart_tool/**
  errors:
    missing_required_param: error
    parameter_assignments: error
    todo: ignore
    deprecated_member_use_from_same_package: ignore


  strong-mode:
    implicit-casts: true
linter:
  rules:
    - annotate_overrides
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - empty_statements
    - always_put_control_body_on_new_line
    - always_declare_return_types
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - avoid_init_to_null
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings
    - unnecessary_brace_in_string_interps
    - prefer_collection_literals
    - avoid_function_literals_in_foreach_calls
    - prefer_iterable_whereType
    - prefer_function_declarations_over_variables
    - unnecessary_lambdas
    - unnecessary_this
    - unnecessary_new
    - unnecessary_const
    - prefer_typing_uninitialized_variables
    - omit_local_variable_types
    - avoid_types_on_closure_parameters
    - avoid_positional_boolean_parameters
    - always_require_non_null_named_parameters
    - always_use_package_imports
    - avoid_empty_else
    - avoid_returning_null_for_void
    - empty_catches
    - empty_constructor_bodies
    - no_duplicate_case_values
    - no_logic_in_create_state
    - non_constant_identifier_names
    - prefer_contains
    - prefer_single_quotes
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - valid_regexps
    - void_checks
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unrelated_type_equality_checks
    - prefer_const_constructors
    - avoid_void_async

dart_code_metrics:


  rules:
    - avoid-wrapping-in-padding
    - no-equal-then-else
    - no-object-declaration
    - prefer-trailing-comma

  metrics-exclude:
    - test/**
  metrics:
    number-of-parameters: 10
    number-of-methods: 32
    source-lines-of-code: 500
    cyclomatic-complexity: 36
